CREATE TABLE IF NOT EXISTS user_recommendation_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    admin_dong_code VARCHAR(20) NOT NULL,
    rank_position INT NOT NULL,
    impression BOOLEAN NOT NULL DEFAULT TRUE,
    clicked_count INT DEFAULT 0,
    liked_count INT DEFAULT 0,
    dwell_time_sec INT DEFAULT 0,
    recommendation_type VARCHAR(30),
    q1 INT,
    q2 INT,
    q3 INT,
    q4 INT,
    q5 INT,
    q6 INT,
    q7 INT,
    q8 INT,
    q9 INT,
    q10 INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_recommendation_logs_user_dong_created (user_id, admin_dong_code, created_at),
    INDEX idx_recommendation_logs_created_at (created_at)
);
