package com.example.padong_server.global.client.seoul;

import java.util.List;

public record SeoulRealtimeData(
        String areaCd,
        String areaNm,
        String thumbnail,
        String roadAddr,
        Double areaPpltnMin,
        Double areaPpltnMax,
        String areaCongestLvl,
        String areaCongestMsg,
        String fcstYn,
        Double fcstPpltnMin,
        Double fcstPpltnMax,
        String fcstTime,
        Double malePpltnRate,
        Double femalePpltnRate,
        Double ppltnRate10,
        Double ppltnRate20,
        Double ppltnRate30,
        Double ppltnRate40,
        Double ppltnRate50,
        Double ppltnRate60,
        Double ppltnRate70,
        String roadTrafficIdx,
        Double roadTrafficSpd,
        String weatherStatus,
        Double temperature,
        Double sensibleTemperature,
        Double humidity,
        Double pm10,
        String pm10Status,
        Double rainChance,
        String eventNm,
        List<String> subwayStationNames,
        List<String> subwayLines,
        List<String> busStopNames,
        List<String> bikeStationNames) {}
