spring:
  application:
    name: padong-be

  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

swagger-config:
  server-url-https: "https://padong.site"
  server-url-http: "http://padong.site"

open-search:
  url: ${OPEN_SEARCH_URL}
  username: ${OPEN_SEARCH_USERNAME}
  password: ${OPEN_SEARCH_PASSWORD}

seoul-open-api:
  base-url: ${SEOUL_OPEN_API_BASE_URL}
  api-key: ${SEOUL_OPEN_API_KEY}

naver:
  news:
    client-id: ${NAVER_NEWS_CLIENT_ID}
    client-secret: ${NAVER_NEWS_CLIENT_SECRET}